# Perfil de dbt para CI (solo validacion de sintaxis)
# En CI usamos un proyecto dummy ya que solo parseamos SQL

dbt_project:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      project: dummy-project-for-ci
      dataset: dummy_dataset
      location: US
      threads: 1
      keyfile: /tmp/dummy-keyfile.json
